### ISSUE TITLE
Release new package on npmjs

### ISSUE THREAD

**Issue by Ashish-Bansal** [prerender/prerender-aws-s3-cache#3]
Hi there!

The package uploaded to npmjs.com[0] doesn't contain latest commit from this repo due to which it throws error related to `undefined variable key`. Please upload new package there.

[0] https://www.npmjs.com/package/prerender-aws-s3-cache

Thanks!

**Comment by thoop** [comment]
Sorry for the delay and thanks for the heads up. The latest code has been pushed as `v1.0.1`.
