### ISSUE TITLE
Cache only specific pages

### ISSUE THREAD

**Issue by captainjackrana** [prerender/prerender-aws-s3-cache#5]
I would like this plugin to only cache certain page requests & not all pages by default. Is there a provision to configure that?

**Comment by thoop** [comment]
You could fork this repo and modify the plugin to only cache certain URLs but that's not something we would add to this repo at this time. I'd like to keep this plugin simple and let people write their own plugins as needed.

If this is something a lot of people ask for, then we might think about implementing it here.
